[all:vars]
ansible_user= "livdev"
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
machine03 ansible_host=35.236.157.252

[all]
machine03 ansible_host=35.236.157.252
