create-machines: 
    ansible-playbook -i inventory.ini playbooks/create-machines-playbook.yml

destroy-vm:
    ansible-playbook -i inventory.ini playbooks/destroy-machine-playbook.yml

set-jenkins:
    ansible-playbook -i inventory.ini playbooks/setup-infra-machine1.yml

set-sonarqube:
    ansible-playbook -i inventory.ini playbooks/setup-infra-machine2.yml

set-nexus:
    ansible-playbook -i inventory.ini playbooks/setup-infra-machine3.yml
    
set-all-machine:
     just set-jenkins
     just set-sonarqube
     just set-nexus
