create-machines: 
    ansible-playbook -i inventory.ini playbooks/create-machines-playbook.yml
destroy-vm:
    ansible-playbook -i inventory.ini playbooks/destroy-machine-playbook.yml
set-infra:
    ansible-playbook -i inventory.ini playbooks/setup-infra-playbook.yml
set-sonarqube:
    ansible-playbook -i inventory.ini playbooks/setup-infra.yml
set-nexus:
    ansible-playbook -i inventory.ini playbooks/setup-infra-machine3.yml
install-zsh:
    ./install_softwares/ohMyZsh.sh
install-docker:
    ./install_softwares/docker.sh
install-just:
    ./install_softwares/just.sh
install-ansible:
    ./install_softwares/ansible.sh
install-nginx_certbot:
    ./install_softwares/nginx_certbot.sh
set-infra-machine:
     just create-machines
     just set-infra
     just set-sonarqube
     just set-nexus
