[all:vars]
ansible_user=livdev
ansible_ssh_private_key_file=/home/livdev/.ssh/id_rsa
ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[local]
localhost ansible_connection=local

[masters]
master01 ansible_host=34.101.123.149
