- name: Install Jenkins
  hosts: machine01
  become: false
  vars_files:
    - ../../vars/machines.yml
  tasks:
    - name: Install fontconfig and openjdk-21
      apt:
        name:
          - fontconfig
          - openjdk-21-jre
        state: present
        update_cache: true
      become: true

    - name: Verify java version
      shell: java -version
      register: java_ver_output

    - name: Show java version
      debug:
        msg: "{{ java_ver_output.stderr }}"

    - name: Add Jenkins GPG key
      shell: |
        sudo wget -O /etc/apt/keyrings/jenkins-keyring.asc \
          https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
      become: true
      args:
        creates: /etc/apt/keyrings/jenkins-keyring.asc

    - name: Add Jenkins repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      become: true
      args:
        creates: /etc/apt/sources.list.d/jenkins.list

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: true
      become: true

    - name: Start and enable jenkins
      service:
        name: jenkins
        state: started
        enabled: true
      become: true

    - name: Wait for jenkins to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 120

    - name: Get jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      become: true
      retries: 5
      delay: 10
      until: jenkins_password.rc == 0

    - name: Show jenkins initial password
      debug:
        msg: "Jenkins initial password: {{ jenkins_password.stdout }}"