

#service_account_path: "/home/kk/credentials/service-account.json"
# adc_file: "credentials file path"
# google_project_id: "project id"
# ssh_pubkey_path: "public key path"
# agent_user: "name"


 

sonarqube_domain: "domain"
jenkins_domain: "domain"
certbot_email: "domain"

# Define machine spec
machine_specs:
  large:
    machine_type: "e2-standard-2"
    zone: "asia-east1-b"
    region: "asia-east1" # for reserving static IP
    disk_size: 60
    disk_type: "pd-standard" # we have hdd(pd-standard) , ssd( pd-ssd)

ubuntu_specs:
  v22:
    image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2204-lts"
  v24:
    image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-2404-lts"


# Define machines that we will create
machines_info:
  # master requirement : RAM 8G, ....
  - name: "machine01"
    machine_type: "{{ machine_specs.large.machine_type }}"
    image: "{{ ubuntu_specs.v22.image }}"
    zone: "{{ machine_specs.large.zone }}"
    region: "{{ machine_specs.large.region }}"
    disk_size: "{{ machine_specs.large.disk_size }}"
    disk_type: "{{ machine_specs.large.disk_type }}"
  - name: "machine02"
    machine_type: "{{ machine_specs.large.machine_type }}"
    image: "{{ ubuntu_specs.v22.image }}"
    zone: "{{ machine_specs.large.zone }}"
    region: "{{ machine_specs.large.region }}"
    disk_size: "{{ machine_specs.large.disk_size }}"
    disk_type: "{{ machine_specs.large.disk_type }}"
  - name: "machine03"
    machine_type: "{{ machine_specs.large.machine_type }}"
    image: "{{ ubuntu_specs.v22.image }}"
    zone: "{{ machine_specs.large.zone }}"
    region: "{{ machine_specs.large.region }}"
    disk_size: "{{ machine_specs.large.disk_size }}"
    disk_type: "{{ machine_specs.large.disk_type }}"


